### ISSUE TITLE
merge changes from last released version v1.30.0001

### ISSUE THREAD

**Issue by mnalis** [mnalis/ironseed_fpc#30]
from https://github.com/karynax/ironseed ? but see also https://github.com/gondur/Ironseed_src ?

it would be good to find source for original DOS `1.20.0016` version, as then I could seed diff `1.20.0016` -> `1.30.0001` and apply to initial `y-salnikov` `fpc 0.0.1` version, and merge upwards from there (like  http://ironseed.net/ source?)

**Comment by nukebloodaxe** [comment]
As far as I know, the ironseed.net source file is the dos build, and the first one that came out.  Looking closer at the file from there, yes, this is the original DOS build, y-salnikov based his Linux fpc port on this.  The ironseed.net site is by one of the original developers and was a good place for a bit of discussion when they had their forum still working.  At the time they were in the process of planning IronSeed 2, but time constraints and life got in the way ;)  (I find it highly amusing that I'm still interested enough in this to actually be doing a Python port, loved the game as a kid 23 years ago when I spotted the demo on a BBS.)
