### ISSUE TITLE
Cargo Display

### ISSUE THREAD

**Issue by nukebloodaxe** [mnalis/ironseed_fpc#31]
I was playing around a little, comparing the old commercial release (1.10) to the current one.  When going to engineering and then clicking on the cargo icon, 1.10 will take you to the cargo screen which is displaying the Gate 7 Door, this door lifts up smoothly to reveal the cargo text.  This does not happen in the current build, so something is probably up; a timing issue?

Also, in the current built (   0) is displayed between the quantity and item name, see 1.10 vs current:
![Ver 1 10 Expected](https://user-images.githubusercontent.com/13254225/89392361-8f0ac700-d75d-11ea-8fcd-9f49e8c814b8.png)
![Odd Display](https://user-images.githubusercontent.com/13254225/89392384-94681180-d75d-11ea-8502-ab02dc30a3a0.png)

**Comment by mnalis** [comment]
I've added a delay now, so doors opening/closing can be seen.

Maybe the video memory access was so slow back then, it didn't need delays. Or original developers decided to throw out that delay (I doubt it, as there is Options/Animations where they could be turned off, and code does check for that option0.

As for the number in parentheses, it is definitely a new feature added between your `v1.10` and released `v1.20.0016` sources.
Game code says it's `rescargo: array[1..250] of word;     {number of each item reserved}` and it looks to me it will be non-zero for example while build of that item is in progress.
