### ISSUE TITLE
fadein/fadeout is sometimes too slow

### ISSUE THREAD

**Issue by mnalis** [mnalis/ironseed_fpc#5]
Fadein/out looks too slow; like it does not depend on `tslice` setting? Show try with various options/timespace settings and make it faster.

for example:
- entering Science / Planet scan (dark screen too long? or is it heavy computation?)
- entering Psy / psy eval
- entering Psy / crew status
- entering Psy / crew comm
- anywhere else?

**Comment by mnalis** [comment]
Also in:
- Ast / sector map

**Comment by mnalis** [comment]
- initiating conversations with aliens

**Comment by nukebloodaxe** [comment]
With the fade routine, much like planet rotation rendering, I'm under the impression it goes as fast as the system running IronSeed.  Whenever I've been reading through the code for conversion, I've not come across timers for it.

**Comment by mnalis** [comment]
@nukebloodaxe actually, there are both `wait()` and `delay()` calls which are used to slow things down. 

However, `delay()` calls should all be (in ideal world) either _very_  short, or (preferrably) always using some multiplier of `tslice` (which can and should be set in `Med / Options / Time slice` depending on your computer speed - for my Intel i3 2.30Ghz laptop, ideal value is probably between `15` and `25`)

Also, FPC version implements time speedup when pressing `Scroll Lock` key, which cuts down on all delays in code as long `Scroll Lock` is pressed down (which could be used to see maximum speed of planet animations for example).

Still, even with reasonable `tslice`, some delays do not feel smooth as they should be, or have `black screen` for few seconds issues (tracked in https://github.com/mnalis/ironseed_fpc/issues/22)

**Comment by mnalis** [comment]
- some parts of the code use `fadefull (step, slice)` which does `delay(slice)` instead of `fading()` (which uses `delay(tslice/2)`)
  they use hardcoded `fadefull(-8, 20)` values.

- fadefull itself uses loop over `fadestep(step)`.

- for example `Psy / psy eval` in `crew2.pas:mainloop()` uses `fadestep(8)` with `delay(tslice*6)`; but other parts might be using other values - check and make them all use same constant/delay function, and then treak. There are few exceptions, though (like `opendoors()` uses `fadestep(1)` with `delay(tslice/4)`)

**Comment by mnalis** [comment]
It works reasonably well on my machine with `tslice=20` in options. Constants are there if some tweaking is needed later, but it looks reasonable, so closing now.
