### ISSUE TITLE
Unable to find usable savedir

### ISSUE THREAD

**Issue by nukebloodaxe** [mnalis/ironseed_fpc#85]
Fresh compilation in Debian and OpenSuse Tumbleweed fails to run with the error "Unable to find usable savedir"

Debian 10:
![image](https://user-images.githubusercontent.com/13254225/96554897-a0528100-1313-11eb-815e-385fa5dd7f99.png)

Tumbleweed:
![image](https://user-images.githubusercontent.com/13254225/96555336-253d9a80-1314-11eb-9dd9-be497eca8498.png)

Works great in Ubuntu 20.4:
![image](https://user-images.githubusercontent.com/13254225/96555165-e9a2d080-1313-11eb-815d-889ff66a2d37.png)

I suspect that some directories are not being generated on the first run, or an assumption is being made about locations.
There is also the possibility that I played a brief test game on the Ubuntu box in the past, and that is why it is working there.

**Comment by mnalis** [comment]
there was a integer size bug with free disk calculation which could provoke this; can you try with latest master 22c1507720b61d379a9f27a111087dae1e1ab801 if it fixes it?

**Comment by mnalis** [comment]
@nukebloodaxe did you perhaps had a chance to see if this fixed the `failed to find usable savedir` ?

**Comment by nukebloodaxe** [comment]
Thank you for the reminder, I've finally had a moment after dealing with the jungle outside my house ;)  So, I've applied the changes and tested it on Debian 10 and Tumbleweed my end, and it's working fine.  Any chance you could set up a pull to bring the changes into the upstream repository my end?

**Comment by mnalis** [comment]
Sure, I wanted first to confirm that fix works - thanks for confirmation! PR sent now
